#!/bin/bash

SOURCE_PATH=$1
if [ -z ${SOURCE_PATH} ]; then
    ORIGIN=$(dirname `which $0`)
    SOURCE_PATH=${ORIGIN}/../dictmentor
fi

echo "Using source path: ${SOURCE_PATH}"

flake8 --max-line-length 120 --ignore=E722 ${SOURCE_PATH}
